name: build

on:
  workflow_dispatch:
  push:

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc
    steps:
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - name: Compile
      run: |
        rustup set profile minimal
        rustup target add --toolchain stable ${{ matrix.target }}
        cargo build --release --target=${{ matrix.target }}
        move target\${{ matrix.target }}\release\*.exe .
        7z a ${{ matrix.target }}.7z moe*.exe
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.target }}.7z
        tag: latest
        overwrite: true
        file_glob: true
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - loongarch64-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: |
        rustup set profile minimal
        rustup target add --toolchain stable ${{ matrix.target }}
        cargo install cross --git https://github.com/cross-rs/cross
        cross build --release --target=${{ matrix.target }}
        mv target/${{ matrix.target }}/release/* .
        rm *.d
        tar acf ${{ matrix.target }}.tar.xz moe*
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.target }}.tar.xz
        tag: latest
        overwrite: true
        file_glob: true
